name: build-page
on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_IMAGE: 221489699002.dkr.ecr.eu-central-1.amazonaws.com/sportalliance/node:20

jobs:
  build:
    runs-on: [self-hosted, linux, arm64, default]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: sportalliance/docker-login@main
        with:
          role: arn:aws:iam::221489699002:role/github-actions-ecr-reader
          region: eu-central-1

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Pull docker image
        run: docker pull $NODE_IMAGE
    
      - name: Build
        run: >
          docker run --rm
          -v $(pwd):/tmp/build -w /tmp/build
          -u $(id -u):$(id -g)
          $NODE_IMAGE
          /bin/bash -c "pnpm install && pnpm run build"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  publish:
    environment:
      name: github-pages
      url: ${{ steps.build.outputs.page_url }}
    runs-on: [self-hosted, linux, arm64, default]
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


